import math
G=6.674*math.pow(10,-11)
m1=5.97600*math.pow(10,24) 
print ('Введите массу второй планеты: ')
m2=float(input())
print ('Введите cтепень 10 у массы второй планеты: ')
stm2=int(input())
print ('Введите расстояние между планетами: ')
R=float(input())
print ('Введите степень 10 у расстояния между планетами: ')
stR=int(input())
m2=m2*math.pow(10,stm2)
R=R*math.pow(10,stR)
print(R)
F=(G*m1*m2)/(R**2)
print(F)